export interface MockFile {
  path: string;
  content: string;
}

export interface MockReply {
  text: string;
  plan: string[];
  files: MockFile[];
}

export function buildMockReply(prompt: string, sessionTitle: string): MockReply {
  const title = sessionTitle.trim() || "My App";

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <header class="site-header">
      <div class="brand">Frank<span>.</span></div>
      <nav class="site-nav">
        <a href="#">Features</a>
        <a href="#">Pricing</a>
        <a href="#" class="cta">Get started</a>
      </nav>
    </header>

    <main>
      <section class="hero">
        <span class="chip">Your idea, built</span>
        <h1>${title}</h1>
        <p class="lead">
          Generated by Frank — a plain HTML/CSS/JS starter you own.
          Open it in any browser and start editing.
        </p>
        <div class="hero-actions">
          <button class="btn-primary" id="startBtn">Get started</button>
          <a href="#features" class="btn-ghost-link">Explore</a>
        </div>
      </section>

      <section class="features" id="features">
        <div class="feature">
          <h3>No build step</h3>
          <p>Just files. Open index.html and it runs.</p>
        </div>
        <div class="feature">
          <h3>Dark by default</h3>
          <p>A calm, deep palette ready to make over.</p>
        </div>
        <div class="feature">
          <h3>Yours to keep</h3>
          <p>Downloaded as plain source, no lock-in.</p>
        </div>
      </section>
    </main>

    <footer class="site-footer">
      <p>Built with Frank</p>
    </footer>

    <script src="script.js"></script>
  </body>
</html>
`;

  const stylesCss = `/* Frank starter theme */
:root {
  --bg: #012624;
  --bg-deep: #011d1c;
  --panel: #003734;
  --text: #edfffe;
  --muted: #bbc7c6;
  --accent: #cbfffc;
  --accent-2: #fde9ff;
  --radius: 16px;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: "Inter", -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  background: radial-gradient(1200px 600px at 50% -10%, var(--panel), var(--bg) 60%), var(--bg-deep);
  color: var(--text);
  line-height: 1.6;
  min-height: 100vh;
}

.site-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 24px 32px;
  border-bottom: 1px solid rgba(187, 199, 198, 0.15);
}

.brand {
  font-weight: 700;
  letter-spacing: -0.02em;
}
.brand span { color: var(--accent); }

.site-nav a { color: var(--muted); text-decoration: none; margin-left: 24px; font-size: 14px; }
.site-nav a:hover { color: var(--text); }
.site-nav .cta {
  padding: 10px 18px;
  border: 1px solid rgba(203, 255, 252, 0.4);
  border-radius: 8px;
  background: #edfffc;
  color: #062421;
  font-weight: 600;
}

.hero {
  text-align: center;
  padding: 96px 24px 72px;
}

.chip {
  display: inline-block;
  padding: 7px 16px;
  border: 1px solid rgba(203, 255, 252, 0.28);
  border-radius: 999px;
  background: rgba(203, 255, 252, 0.06);
  color: var(--accent-2);
  font-size: 12px;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  margin-bottom: 24px;
}

.hero h1 {
  font-size: clamp(40px, 7vw, 72px);
  line-height: 1.05;
  letter-spacing: -0.04em;
  margin-bottom: 16px;
}

.lead {
  max-width: 520px;
  margin: 0 auto 32px;
  color: var(--muted);
  font-size: 18px;
}

.hero-actions { display: flex; gap: 16px; justify-content: center; align-items: center; }

.btn-primary {
  padding: 14px 28px;
  border-radius: 8px;
  border: none;
  background: var(--accent);
  color: #062421;
  font-weight: 600;
  cursor: pointer;
}
.btn-primary:hover { background: #ffffff; }

.btn-ghost-link { color: var(--muted); text-decoration: none; font-size: 15px; }
.btn-ghost-link:hover { color: var(--text); }

.features {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 20px;
  max-width: 960px;
  margin: 0 auto;
  padding: 24px;
}

.feature {
  border: 1px solid rgba(187, 199, 198, 0.15);
  border-radius: var(--radius);
  background: rgba(2, 55, 52, 0.4);
  padding: 28px;
}

.feature h3 { margin-bottom: 8px; font-size: 18px; }
.feature p { color: var(--muted); font-size: 15px; }

.site-footer {
  text-align: center;
  padding: 48px 24px;
  color: var(--muted);
  font-size: 14px;
}

body.flash .btn-primary { animation: pop 0.4s ease; }

@keyframes pop {
  50% { transform: scale(1.08); }
}
`;

  const scriptJs = `// Frank starter interactivity
const startBtn = document.getElementById("startBtn");

if (startBtn) {
  startBtn.addEventListener("click", () => {
    document.body.classList.add("flash");
    setTimeout(() => document.body.classList.remove("flash"), 500);
    console.log("Frank starter is running ✦");
  });
}

document.addEventListener("keydown", (e) => {
  if (e.key === "Escape") {
    document.body.classList.remove("flash");
  }
});
`;

  return {
    text: "Done — here's a ready-to-open starter project. It's plain HTML/CSS/JS, no build step, so you can run it by opening index.html in any browser. Grab the ZIP below and tweak away. Want me to change the palette, add a section, or swap the layout?",
    plan: [
      "Scaffold the project structure (3 files)",
      "Build the page layout",
      "Apply the dark Frank palette",
      "Add lightweight interactions",
    ],
    files: [
      { path: "index.html", content: indexHtml },
      { path: "styles.css", content: stylesCss },
      { path: "script.js", content: scriptJs },
    ],
  };
}